# Курсовая работа (проект)

## Тема: "Исследование котировок акций для обнаружения волатильных паттернов и рыночных трендов"

### Ченцов Егор, ИД24-3

## Задание на семинар 2.1:

### Задание

2.1. Проанализировать цели проекта. С точки зрения бизнеса, определить бизнес-цели и критерии их достижения, с точки зрения науки, задать границы исследования в рамках выбранной темы, описать объект и предмет исследования, сформулировать аналитическую гипотезу.

### Ответ

**Цель работы**
 
Продемонстрировать владение основными навыками работы с большими данными, владение основными инструментальными средствами библиотек языка программирования Python, методами и приемами подготовительного и описательного анализа данных, методами слияния разнородных данных, алгоритмов анализа данных, средствами визуализации данных, умение делать выводы из проведенного анализа.
 
**Задания для выполнения**
 
**1. Выбрать одну из предложенных тем курсовой работы. Одна тема – один студент, темы повторяться не должны.**
 
Для курсового проекта я выбрал тему: “Исследование котировок акций для обнаружения волатильных паттернов и рыночных трендов”. 
 
В работе я буду использовать котировки акций российских компаний с Московской биржи, а также связанные с ними рыночные, макроэкономические и новостные факторы. Я буду не просто анализировать финансовые данные, а сосредоточусь на поиске волатильных паттернов и определении ожидаемого направления движения цен в будущем. 
 
Практическая значимость состоит в создании аналитического решения, которое можно воспроизвести и использовать в собственных целях. Оно включает сбор различных типов данных, их обработку (ETL), расчет признаков, применение статистических методов и машинного обучения, сравнение моделей, замеры скорости работы и создание интерактивного дашборда. 
 
**2. Выполнить исследование темы на основе методологии CRISP-DM  (Cross-Industry Standard Process for Data Mining), включая следующие шаги:**
 
**2.1. Проанализировать цели проекта. С точки зрения бизнеса, определить бизнес-цели и критерии их достижения, с точки зрения науки, задать границы исследования в рамках выбранной темы, описать объект и предмет исследования, сформулировать аналитическую гипотезу.**
 
Бизнес-цель проекта: создать инструмент, который по открытым и разнообразным данным будет сигнализировать о изменении тренда акций и искать повторяющиеся паттерны для улучшения предсказания аналитикам и инвесторам.
 
Российский фондовый рынок имеет высокую волатильность, поэтому инвесторам важно знать будущее движение акции. Если такое движение удастся распознать в самом начале, то получится скорректировать и пересмотреть свой инвестиционный портфель. 
 
Критерии достижения цели: инструмент обученный на исторических данных будет устойчиво определять периоды повышенной волатильности от спокойной. При этом адаптируемый под разные типы данных и воспроизводимый на новых. В момент обучения не будет использоваться информация из будущего, чтобы предотвратить переобучение модели
 
Исследовательская задача: Проверить совместимость различных котировок, факторов и данных для классификации ожидаемого направления на горизонте 5 дней и сравнить с моделью, построенную на исходных котировках.
 
Гипотеза: Улучшается ли качество предсказания тренда акции при добавлении технических, макроэкономических и текстовых признаков относительно базовой модели обученной на одних котировках.
 
Дополнительная гипотеза: Получиться ли определить при правильном предсказании, что сильнее всего повлияло на направление движения цены акции
 
Границы исследования: Период анализа взят период с 2022 года, поскольку после санкционных ограничений и сокращения иностранного финансирования, рыночные условия на бирже сильно изменились, и более ранние данные отражают не правдивую и не реалистичную в нынешних условиях среду
 
Объект исследования: котировка акций и рыночные тренды на Московской бирже
 
Предмет исследования: статистические и технические зависимости между историческими котировками, макроэкономическими факторами, новостными статьями и будущим направлением движения котировок 
 
Проверка гипотезы: Для проверки будут реализованы и обучены три модели - Logistic Regression, Random Forest, Gradient Boosting

## Задание на семинар 2.2:

### Задание

2.2. Подобрать источники данных по требованиям п.3 и изучить их. Выбрать числовые и категориальные характеристики, представляющие аналитический портрет состояния объекта исследования и факторов влияния.  
  
3. Среди открытых источников данных по теме исследования найти:  
3.1. не менее 1 реляционного набора данных;  
3.2. не менее 1 иерархического набора данных (формат XML);  
3.3. не менее 1 источника с API с выдачей в формате JSON;  
3.4. не менее 1 источника неструктурированных данных: в текстовом виде (статьи, посты, сообщения, сайты), аудио или видео. Допустимо получение по API.
Каждый использованный набор данных должен описывать множество объектов, относящихся к теме исследования, в не менее чем 3-х категориальных аспектах и не менее чем 3-мя числовыми характеристиками. Преимуществом будет наличие характеристики времени (дата и\или время). Весь список источников должен охватывать не только предмет исследования, но и данные описывающие возможные факторы влияния.

### Начало поиска (теория)

Ищем датасеты отсюда:  
https://www.kaggle.com/datasets  
https://huggingface.co/datasets

Разделим поиск на 4 группы: сами котировки, рыночные/макроэкономические факторы, новости и дополнительные характеристики компаний

#### Основные слова для поиска датасетов

**1. Основные котировки акций**

- Russian stock market
- Russian stocks
- Russia stock market
- MOEX stocks
- Moscow Exchange
- MOEX
- MICEX
- Russian stock prices
- Russian stock market data
- MOEX historical data
- Russian shares
- stock prices Russia
- stock market time series
- OHLCV stocks
- stock market OHLC
- historical stock prices

**Особенно полезны сочетания:**

- Russian stock market historical data
- MOEX historical stock prices
- Russian stocks OHLCV
- Moscow Exchange stock prices

**2. Волатильность и технические показатели**

- stock volatility
- stock returns
- historical volatility
- market volatility
- technical indicators
- RSI stock
- MACD stock
- moving average stock
- Bollinger Bands
- stock market trends
- stock trend prediction
- financial time series

**3. Рыночные и макроэкономические факторы**

- Russian economy
- Russia economic indicators
- Russia macroeconomic data
- Russian inflation
- Russian interest rate
- Central Bank Russia
- Bank of Russia
- USD RUB
- CNY RUB
- oil prices
- Brent oil
- Russian government bonds
- OFZ
- Russian bond yields
- IMOEX
- MOEX index
- RTS index

**Можно также искать:**

- Russia economic indicators time series
- Russia inflation interest rate exchange rate
- Russian financial market data

**4. Новости и текстовые данные**

- Russian financial news
- Russian stock market news
- Russian stock news
- financial news
- stock market news
- financial news sentiment
- Russian news sentiment
- stock market sentiment
- financial sentiment
- Russian economic news
- Russian business news

**Более обширные:**

- Russian financial news dataset
- Russian stock market news dataset
- financial news sentiment dataset
- stock news sentiment

#### Пример норм датасета

**Категориальные:**
- Ticker
- Company
- Sector

**Числовые:**
- Open
- High
- Low
- Close
- Volume

**Время:**
- Date

#### Желательные столбы в датасетах

**1. Основные котировки акций**  
Ticker + Company + Sector + Date + Open + High + Low + Close + Volume  
**2. Рыночные и макроэкономические факторы**  
Russia/Indicator + Date + Value + Unit + Source  
(инфляция, ключевая ставка и тд.)  
**3. Новости и текстовые данные**  
Date + Source + Company/Ticker + Category + Title/Text

### Поиск и проверка датасетов

In [4]:
%pip install pandas requests beautifulsoup4

Requirement already satisfied: pandas in c:\users\home\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: requests in c:\users\home\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: beautifulsoup4 in c:\users\home\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\home\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\home\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\home\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\home\anaconda3\lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\home\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\home\anaconda3\lib\site-packages (from requests) (2024.7.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\home\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: six>=1.5 in c:\users\home\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [10]:
import pandas as pd
import requests
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup

In [28]:
date = '2025-09-01'  # любую дату, главное с закрытым торгом
base = 'https://iss.moex.com/iss/'

#### 3.1. Реляционный набор: две связанные таблицы MOEX.
История торгов + справочник бумаг. Общий ключ — код бумаги SECID  
Для знакомства с данными берём первые 100 строк истории за один день

Котировки описывают цену, объём и торговую активность акций  
Таблицы связаны по коду бумаги

In [15]:
url = base + 'history/engines/stock/markets/shares/securities.json'

r = requests.get(url, params={'date': date, 'iss.meta': 'off'}, timeout=30)
r.raise_for_status()

In [17]:
data = r.json()['history']
prices = pd.DataFrame(data['data'], columns=data['columns'])

In [19]:
parts = []  # Справочник получаем по страницам

for start in range(0, 10000, 100):
    r = requests.get(base + 'securities.json', params={'engine': 'stock', 'market': 'shares', 'start': start, 'iss.meta': 'off'}, timeout=30)
    r.raise_for_status()
    data = r.json()['securities']
    if not data['data']:
        break
    parts.append(pd.DataFrame(data['data'], columns=data['columns']))
else:
    raise ValueError('Нужно увеличить диапазон страниц справочника')
securities = pd.concat(parts, ignore_index=True)

stocks = prices.merge(securities[['secid', 'type']], left_on='SECID',right_on='secid', how='left', validate='many_to_one')
stocks = stocks[['SECID', 'BOARDID', 'CURRENCYID', 'type', 'TRADEDATE','OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME', 'VALUE', 'NUMTRADES']]

In [22]:
print('Строк справочника:', len(securities))

Строк справочника: 2523

In [56]:
display(stocks.head(10))

,SECID,BOARDID,CURRENCYID,type,TRADEDATE,OPEN,HIGH,LOW,CLOSE,VOLUME,VALUE,NUMTRADES
0,ABIO,TQBR,SUR,common_share,2025-09-01,76.840,78.520,76.720,77.500,229930,1.792310e+07,1445
1,ABRD,TQBR,SUR,common_share,2025-09-01,180.000,181.000,178.800,179.600,20220,3.636462e+06,402
2,AFKS,SMAL,SUR,common_share,2025-09-01,16.556,16.578,16.069,16.555,330,5.452380e+03,37
3,AFKS,TQBR,SUR,common_share,2025-09-01,16.453,16.530,16.001,16.072,48356800,7.862291e+08,15868
4,AFLT,SMAL,SUR,common_share,2025-09-01,62.010,63.280,62.010,63.280,2,1.252900e+02,2
5,AFLT,TQBR,SUR,common_share,2025-09-01,62.130,62.940,61.200,61.260,18061650,1.122741e+09,32503
6,AKAI,TQTF,SUR,exchange_ppif,2025-09-01,110.540,110.840,109.510,110.310,526,5.807218e+04,149
7,AKBC,TQTF,SUR,exchange_ppif,2025-09-01,103.300,104.300,102.500,103.000,1660,1.720971e+05,292
8,AKFB,TQTF,SUR,exchange_ppif,2025-09-01,120.000,120.250,119.340,120.140,2935908,3.526396e+08,1595
9,AKGD,TQTF,SUR,exchange_ppif,2025-09-01,201.240,203.500,201.240,202.440,76386,1.549475e+07,2579

#### 3.2. XML: история торгов в иерархическом формате

Структура: document -> data -> rows -> row. Первая страница ответа

Биржевые наблюдения в XML

In [34]:
url_xml = base + 'history/engines/stock/markets/shares/securities.xml'

r = requests.get(url_xml, params={'date': date}, timeout=30)
r.raise_for_status()

In [36]:
root = ET.fromstring(r.content)
rows = [row.attrib for row in root.findall("./data[@id='history']/rows/row")]
xml_data = pd.DataFrame(rows)[['SECID', 'BOARDID', 'CURRENCYID', 'TRADEDATE', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME']]

In [54]:
display(xml_data.head(10))

,SECID,BOARDID,CURRENCYID,TRADEDATE,OPEN,HIGH,LOW,CLOSE,VOLUME
0,ABIO,TQBR,SUR,2025-09-01,76.84,78.52,76.72,77.5,229930
1,ABRD,TQBR,SUR,2025-09-01,180,181,178.8,179.6,20220
2,AFKS,SMAL,SUR,2025-09-01,16.556,16.578,16.069,16.555,330
3,AFKS,TQBR,SUR,2025-09-01,16.453,16.53,16.001,16.072,48356800
4,AFLT,SMAL,SUR,2025-09-01,62.01,63.28,62.01,63.28,2
5,AFLT,TQBR,SUR,2025-09-01,62.13,62.94,61.2,61.26,18061650
6,AKAI,TQTF,SUR,2025-09-01,110.54,110.84,109.51,110.31,526
7,AKBC,TQTF,SUR,2025-09-01,103.3,104.3,102.5,103,1660
8,AKFB,TQTF,SUR,2025-09-01,120,120.25,119.34,120.14,2935908
9,AKGD,TQTF,SUR,2025-09-01,201.24,203.5,201.24,202.44,76386

#### 3.3. JSON API: индексы как возможные факторы влияния на акции

In [42]:
url_json = base + 'history/engines/stock/markets/index/securities.json'

In [44]:
parts = []

for start in range(0, 10000, 100):
    r = requests.get(url_json, params={'date': date, 'start': start, 'iss.meta': 'off'}, timeout=30)
    r.raise_for_status()
    data = r.json()['history']
    if not data['data']:
        break
    parts.append(pd.DataFrame(data['data'], columns=data['columns']))
else:
    raise ValueError('Нужно увеличить диапазон страниц индексов')

indices = pd.concat(parts, ignore_index=True)
indices = indices[['SECID', 'BOARDID', 'CURRENCYID', 'TRADEDATE', 'OPEN', 'HIGH', 'LOW', 'CLOSE']]

C:\Users\Home\AppData\Local\Temp\ipykernel_4648\3743121302.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  indices = pd.concat(parts, ignore_index=True)

In [48]:
print('В ответе есть индексы и расчётные показатели фондов iNAV')
print('IMOEX и RTSI — рынок акций, RGBI — облигации, RVI — рыночная волатильность')

В ответе есть индексы и расчётные показатели фондов iNAV
IMOEX и RTSI — рынок акций, RGBI — облигации, RVI — рыночная волатильность

In [50]:
display(indices[indices['SECID'].isin(['IMOEX', 'RTSI', 'RGBI', 'RVI'])])

     SECID BOARDID CURRENCYID   TRADEDATE     OPEN     HIGH      LOW    CLOSE
121  IMOEX    SNDX        RUB  2025-09-01  2923.49  2925.02  2886.97  2886.97
233   RGBI    SNDX        RUB  2025-09-01   119.24   119.44   119.24   119.35
241   RTSI    RTSI        USD  2025-09-01  1138.10  1147.05  1130.80  1130.80
469    RVI    RTSI       None  2025-09-01    31.76    33.73    30.62    32.61

#### 3.4. Текстовые данные: полные новости Банка России
RSS нужен для поиска ссылок, сами тексты получаем со страниц статей

In [60]:
url_news = 'https://www.cbr.ru/rss/eventrss'

r = requests.get(url_news, timeout=30)
r.raise_for_status()
rss = ET.fromstring(r.content)

In [63]:
rows = []

for item in rss.findall('./channel/item')[:10]:
    link = item.findtext('link')
    
    r = requests.get(link, timeout=30)
    r.raise_for_status()
    
    soup = BeautifulSoup(r.content, 'html.parser')
    blocks = soup.select('.lead-text, .landing-text, .full-text')
    text = ' '.join(block.get_text(' ', strip=True) for block in blocks)
    
    rows.append({'title': item.findtext('title'), 'date': item.findtext('pubDate'), 'url': link, 'text': text})

news = pd.DataFrame(rows)

Простая разметка: тема, аудитория и наличие слов о росте/снижении

In [66]:
news['topic'] = 'другое'

news.loc[news['text'].str.contains('инфляц|ставк', case=False), 'topic'] = 'ставки и инфляция'
news.loc[news['text'].str.contains('валют|курс рубл', case=False), 'topic'] = 'валюты'

news['audience'] = 'общая'

news.loc[news['text'].str.contains('предприят|компани', case=False), 'audience'] = 'бизнес'
news.loc[news['text'].str.contains('граждан|населен', case=False), 'audience'] = 'население'

news['direction'] = 'не определено'

news.loc[news['text'].str.contains('рост|повыш', case=False), 'direction'] = 'есть рост'
news.loc[news['text'].str.contains('сниж|сокращ', case=False), 'direction'] = 'есть снижение'

news['characters'] = news['text'].str.len()
news['words'] = news['text'].str.findall(r'\b[А-Яа-яЁёA-Za-z]+\b').str.len()
news['numbers'] = news['text'].str.findall(r'\d+(?:[.,]\d+)?').str.len()

In [74]:
print('Фактор: макроэкономические сообщения. Категории и числа вычислены из текста')
print('Разметка приблизительная: *direction* не означает влияние новости на цену акции')

Фактор: макроэкономические сообщения. Категории и числа вычислены из текста
Разметка приблизительная: *direction* не означает влияние новости на цену акции

In [72]:
display(news[['title', 'topic', 'audience', 'direction', 'characters', 'words', 'numbers']].head(8))

,title,topic,audience,direction,characters,words,numbers
0,В большинстве регионов в сентябре цены выросли...,ставки и инфляция,общая,есть снижение,1044,146,0
1,Приглашаем исследователей принять участие в на...,другое,общая,не определено,784,100,7
2,Банк России провел третий Евразийский круглый ...,валюты,общая,не определено,797,100,1
3,Доклад «Региональная экономика»: потребительск...,другое,бизнес,есть снижение,1008,127,1
4,Показатели устойчивой инфляции в сентябре прак...,валюты,общая,есть рост,903,119,3
5,О чем говорят тренды: умеренный рост экономики...,ставки и инфляция,общая,есть рост,595,76,2
6,Мониторинг предприятий: деловая активность в о...,другое,бизнес,есть рост,888,110,6
7,Онлайн-занятия по финансовой грамотности для с...,другое,население,не определено,1805,225,5

#### Характеристики, которые выбраны для каждого набора

In [77]:
datasets = {'Акции': stocks, 'XML': xml_data, 'Индексы JSON': indices, 'Новости': news}

categories = {
    'Акции': ['SECID', 'BOARDID', 'CURRENCYID', 'type'],
    'XML': ['SECID', 'BOARDID', 'CURRENCYID'],
    'Индексы JSON': ['SECID', 'BOARDID', 'CURRENCYID'],
    'Новости': ['topic', 'audience', 'direction']}

numbers = {
    'Акции': ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME', 'VALUE', 'NUMTRADES'],
    'XML': ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME'],
    'Индексы JSON': ['OPEN', 'HIGH', 'LOW', 'CLOSE'],
    'Новости': ['characters', 'words', 'numbers']}

meaning = {
    'SECID': 'Код бумаги или индекса', 'BOARDID': 'Режим торгов',
    'CURRENCYID': 'Валюта расчётов', 'type': 'Тип бумаги из текущего справочника',
    'OPEN': 'Цена открытия / начальное значение индекса',
    'HIGH': 'Максимум за день', 'LOW': 'Минимум за день',
    'CLOSE': 'Цена / значение закрытия', 'VOLUME': 'Объём торгов',
    'VALUE': 'Денежный оборот в валюте расчётов', 'NUMTRADES': 'Количество сделок',
    'TRADEDATE': 'Дата торгов', 'date': 'Время публикации с часовым поясом',
    'title': 'Заголовок', 'text': 'Полный текст', 'url': 'Ссылка на статью',
    'topic': 'Тема по ключевым словам', 'audience': 'Предполагаемая аудитория',
    'direction': 'Упомянутое изменение; при двух совпадениях выбранное снижение',
    'characters': 'Количество символов', 'words': 'Количество слов',
    'numbers': 'Количество упоминаний чисел'}

In [79]:
display(pd.DataFrame(meaning.items(), columns=['Поле', 'Значение']))

          Поле                                           Значение
0        SECID                             Код бумаги или индекса
1      BOARDID                                       Режим торгов
2   CURRENCYID                                    Валюта расчётов
3         type                 Тип бумаги из текущего справочника
4         OPEN         Цена открытия / начальное значение индекса
5         HIGH                                   Максимум за день
6          LOW                                    Минимум за день
7        CLOSE                           Цена / значение закрытия
8       VOLUME                                       Объём торгов
9        VALUE                  Денежный оборот в валюте расчётов
10   NUMTRADES                                  Количество сделок
11   TRADEDATE                                        Дата торгов
12        date                  Время публикации с часовым поясом
13       title                                          Заголовок
14        text                                       Полный текст
15         url                                   Ссылка на статью
16       topic                            Тема по ключевым словам
17    audience                           Предполагаемая аудитория
18   direction  Упомянутое изменение; при двух совпадениях выб...
19  characters                                Количество символов
20       words                                    Количество слов
21     numbers                        Количество упоминаний чисел

#### Итоговое описание всех датасетов

In [86]:
def describe_data(name, df):
    
    df.replace('', pd.NA, inplace=True)
    
    for col in numbers[name]:
        df[col] = pd.to_numeric(df[col], errors='raise')
    
    for col in categories[name]:
        df[col] = df[col].astype('category')
    
    date_col = 'date' if name == 'Новости' else 'TRADEDATE'
    df[date_col] = pd.to_datetime(df[date_col], utc=True, errors='raise')
    
    print('\n', name, '— строк:', len(df), 'столбцов:', len(df.columns))
    print('Категориальные:', categories[name])
    print('Числовые:', numbers[name])
    print('Диапазон дат:', df[date_col].min(), '—', df[date_col].max())
    display(pd.DataFrame({'Тип': df.dtypes.astype(str), 'Пропуски': df.isna().sum(), 'Пропуски, %': (df.isna().mean()*100).round(2), 'Уникальные': df.nunique()}))
    display(df[numbers[name]].agg(['min', 'max']).T)
    print('Полных дубликатов:', df.duplicated().sum())

In [88]:
for name, df in datasets.items():
    describe_data(name, df)

 Акции — строк: 100 столбцов: 12
Категориальные: ['SECID', 'BOARDID', 'CURRENCYID', 'type']
Числовые: ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME', 'VALUE', 'NUMTRADES']
Диапазон дат: 2025-09-01 00:00:00+00:00 — 2025-09-01 00:00:00+00:00

                            Тип  Пропуски  Пропуски, %  Уникальные
SECID                  category         0          0.0          84
BOARDID                category         0          0.0           4
CURRENCYID             category         0          0.0           2
type                   category         0          0.0           3
TRADEDATE   datetime64[ns, UTC]         0          0.0           1
OPEN                    float64         2          2.0          98
HIGH                    float64         2          2.0          98
LOW                     float64         2          2.0          98
CLOSE                   float64         2          2.0          98
VOLUME                    int64         0          0.0          95
VALUE                   float64         0          0.0          99
NUMTRADES                 int64         0          0.0          86

               min           max
OPEN       0.07400  1.840000e+04
HIGH       0.07456  1.885000e+04
LOW        0.07000  1.805000e+04
CLOSE      0.07088  1.885000e+04
VOLUME     0.00000  3.546570e+09
VALUE      0.00000  5.627690e+09
NUMTRADES  0.00000  7.942520e+05

Полных дубликатов: 0

 XML — строк: 100 столбцов: 9
Категориальные: ['SECID', 'BOARDID', 'CURRENCYID']
Числовые: ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME']
Диапазон дат: 2025-09-01 00:00:00+00:00 — 2025-09-01 00:00:00+00:00

                            Тип  Пропуски  Пропуски, %  Уникальные
SECID                  category         0          0.0          84
BOARDID                category         0          0.0           4
CURRENCYID             category         0          0.0           2
TRADEDATE   datetime64[ns, UTC]         0          0.0           1
OPEN                    float64         2          2.0          98
HIGH                    float64         2          2.0          98
LOW                     float64         2          2.0          98
CLOSE                   float64         2          2.0          98
VOLUME                    int64         0          0.0          95

            min           max
OPEN    0.07400  1.840000e+04
HIGH    0.07456  1.885000e+04
LOW     0.07000  1.805000e+04
CLOSE   0.07088  1.885000e+04
VOLUME  0.00000  3.546570e+09

Полных дубликатов: 0

 Индексы JSON — строк: 534 столбцов: 8
Категориальные: ['SECID', 'BOARDID', 'CURRENCYID']
Числовые: ['OPEN', 'HIGH', 'LOW', 'CLOSE']
Диапазон дат: 2025-09-01 00:00:00+00:00 — 2025-09-01 00:00:00+00:00

                            Тип  Пропуски  Пропуски, %  Уникальные
SECID                  category         0         0.00         534
BOARDID                category         0         0.00           6
CURRENCYID             category         1         0.19           4
TRADEDATE   datetime64[ns, UTC]         0         0.00           1
OPEN                    float64         2         0.37         523
HIGH                    float64         2         0.37         519
LOW                     float64         2         0.37         522
CLOSE                   float64         2         0.37         523

        min        max
OPEN  -0.45  151327.31
HIGH  -0.23  151617.67
LOW   -0.48  151137.32
CLOSE -0.45  151436.27

Полных дубликатов: 0

 Новости — строк: 10 столбцов: 10
Категориальные: ['topic', 'audience', 'direction']
Числовые: ['characters', 'words', 'numbers']
Диапазон дат: 2026-10-09 14:15:00+00:00 — 2026-10-16 09:46:00+00:00

                            Тип  Пропуски  Пропуски, %  Уникальные
title                    object         0          0.0          10
date        datetime64[ns, UTC]         0          0.0          10
url                      object         0          0.0          10
text                     object         0          0.0          10
topic                  category         0          0.0           3
audience               category         0          0.0           3
direction              category         0          0.0           3
characters                int64         0          0.0          10
words                     int64         0          0.0           9
numbers                   int64         0          0.0           8

            min    max
characters  595  11006
words        76   1560
numbers       0     16

Полных дубликатов: 0

Проверки качества данных

In [91]:
checks = []

for name, df in datasets.items():
    checks.append({'Проверка': name + ': минимум 3 категории и 3 числа', 'Пройдено': len(categories[name]) >= 3 and len(numbers[name]) >= 3})
    checks.append({'Проверка': name + ': нет полных дубликатов', 'Пройдено': df.duplicated().sum() == 0})

for name in ['Акции', 'XML', 'Индексы JSON']:
    data = datasets[name][['OPEN', 'HIGH', 'LOW', 'CLOSE']].dropna()
    correct = (data['LOW'] <= data['OPEN']) & (data['OPEN'] <= data['HIGH'])
    correct = correct & (data['LOW'] <= data['CLOSE']) & (data['CLOSE'] <= data['HIGH'])
    checks.append({'Проверка': name + ': Low ≤ Open, Close ≤ High', 'Пройдено': bool(correct.all())})

checks.append({'Проверка': 'JOIN сохранил число строк', 'Пройдено': len(stocks) == len(prices)})
checks.append({'Проверка': 'Типы бумаг найдены', 'Пройдено': not stocks['type'].isna().any()})
checks.append({'Проверка': 'Объёмы неотрицательны', 'Пройдено': bool(stocks['VOLUME'].dropna().ge(0).all())})
checks.append({'Проверка': 'Тексты статей извлечены', 'Пройдено': bool(news['characters'].ge(100).all())})
checks.append({'Проверка': 'Нет повторных ссылок новостей', 'Пройдено': news['url'].is_unique})

In [103]:
print('Пропуски цен не заполняем нулями: они могут быть связаны с отсутствием торгов')
print('Новости из текущей RSS и исторические котировки пока не объединяем: даты различаются')
print('У текстов условие 3+3 выполнено после обработки, а не по исходным готовым полям')

Пропуски цен не заполняем нулями: они могут быть связаны с отсутствием торгов
Новости из текущей RSS и исторические котировки пока не объединяем: даты различаются
У текстов условие 3+3 выполнено после обработки, а не по исходным готовым полям

In [99]:
display(pd.DataFrame(checks))

                                       Проверка  Пройдено
0          Акции: минимум 3 категории и 3 числа      True
1                  Акции: нет полных дубликатов      True
2            XML: минимум 3 категории и 3 числа      True
3                    XML: нет полных дубликатов      True
4   Индексы JSON: минимум 3 категории и 3 числа      True
5           Индексы JSON: нет полных дубликатов      True
6        Новости: минимум 3 категории и 3 числа      True
7                Новости: нет полных дубликатов      True
8               Акции: Low ≤ Open, Close ≤ High      True
9                 XML: Low ≤ Open, Close ≤ High      True
10       Индексы JSON: Low ≤ Open, Close ≤ High      True
11                    JOIN сохранил число строк      True
12                           Типы бумаг найдены      True
13                        Объёмы неотрицательны      True
14                      Тексты статей извлечены      True
15                Нет повторных ссылок новостей      True

In [97]:
print('Доля пройденных проверок:', round(pd.DataFrame(checks)['Пройдено'].mean()*100, 1), '%')

Доля пройденных проверок: 100.0 %

### Ссылки на использованные источники

In [108]:
sources = pd.DataFrame({
    'Источник': ['История акций', 'Справочник бумаг', 'XML', 'Индексы JSON', 'Новости ЦБ', 'MOEX ISS'],
    'Ссылка': [base+'history/engines/stock/markets/shares/securities.json?date='+date,
               base+'securities.json?engine=stock&market=shares', url_xml+'?date='+date,
               url_json+'?date='+date, url_news, 'https://www.moex.com/a2920']})

In [110]:
for _, row in sources.iterrows():
    print(row['Источник'] + ': ' + row['Ссылка'])

История акций: https://iss.moex.com/iss/history/engines/stock/markets/shares/securities.json?date=2025-09-01
Справочник бумаг: https://iss.moex.com/iss/securities.json?engine=stock&market=shares
XML: https://iss.moex.com/iss/history/engines/stock/markets/shares/securities.xml?date=2025-09-01
Индексы JSON: https://iss.moex.com/iss/history/engines/stock/markets/index/securities.json?date=2025-09-01
Новости ЦБ: https://www.cbr.ru/rss/eventrss
MOEX ISS: https://www.moex.com/a2920